title: Abhinaya Gyawali
description: Data Scientist | Machine Learning | Data Analytics | Python | SQL | AWS-Certified | Ex-DevOps Engineer
theme: jekyll-theme-minimal

logo: profile_image.jpeg

location: Pennsylvania, USA
email: abhinaya7@gmail.com
github_username: abhinaya1
linkedin_username: abhinaya-gyawali
